---
kind: Template
apiVersion: v1
metadata:
  name: tf-secret
  annotations:
    description: Tensorflow Build environment secret variables
    openshift.io/display-name: Tensorflow Build Secrets
    version: 0.1.0
  labels:
    app: tf-build

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: tf-secret
      labels:
        app: tf-build
    stringData:
      git-release-repo: ${GIT_RELEASE_REPO}
      git-token: ${GIT_TOKEN}

parameters:
  - description: GitHub repository to release tensorflow wheels.
    displayName: GitHub release Repository
    required: true
    name: GIT_RELEASE_REPO
    value: "https://github.com/AICoE/tensorflow-wheels.git"

  - description: Github oauth token for releases.
    displayName: github oauth token
    required: true
    name: GIT_TOKEN
